### PR TITLE
Respond to IdAck with IdAck

### PR DESCRIPTION
**Pull request by ranomine**
IPA protocol requires the client to respond with IdAck to a IdAck message

### CODE REVIEW

**Comment by ranomine** [comment]
We add the possibility for the IPA stack to reply to IdentityAck

**Comment by zecke** [comment]
Looks fine but I am slightly worried about loops? Do we get an IdAck as response already?

**Comment by ranomine** [comment]
Here's a trace of the exchange when the connection gets established.
Osmo-STP sends an ID ack and expects an ID Ack in return.

Le jeu. 20 janv. 2022 à 14:13, Holger Freyther ***@***.***> a
écrit :

**Comment by zecke** [comment]
Okay. We are not pro-actively sending the ID ACK so will not immediately cause loops

**Pull request merged**
